config/routes.rb
Rails.application.routes.draw do


root "sessions#welcome"
get 'pages', to: 'pages#index'#, as:'pages'  


####### OmniAuth #################   google ###################################
# get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
get '/auth/:provider/callback', to: 'sessions#omniauth'  #<= makes more dynamic
###############################################################################


########  SIGN UP ROUTES (custom)  ######## 
get '/signup', to: "users#new"
post '/signup', to: "users#create"


########  SESSIONS ROUTES  ########
get 'login', to: "sessions#new"
post 'login', to: "sessions#create"
delete 'logout', to: "sessions#destroy"
#################################################################



#################rested routes####################################
  resources :users, :except => [:index] do
    resources :user_stylists
  end
  resources :user_stylists

  resources :stylists, :except => [:destroy]

#################################################################


# match '*path' => redirect('/'), :via => [:get, :post] 
### localhost:3000/qwefkfqasdkfas;dlkfn to the root path/

end











# 🚧 # THINGS WE HAVE TO BUILD OUT
# get 'welcome', to: "sessions#welcome" 
# 🚧 #
######## 
# REMEMBER FOLKS  ::  NO resource :sessions 
#################################################################



  # get 'stylists/index'
  # get 'stylists/show'
  # get 'stylists/new'
  # get 'stylists/create'
  # get 'stylists/edit'
  # get 'stylists/update'
  # get 'stylists/destroy'
  # get 'sessions/new'
  # get 'sessions/create'
  # get 'sessions/login'
  # get 'sessions/destroy'
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/user.rb
class User < ApplicationRecord
    has_many :user_stylists
    has_many :stylists, through: :user_stylists

   

    validates_presence_of :username, :email
    validates_uniqueness_of :username, :email 

    has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :find_user, only: [:show, :edit, :update, :destroy]

    skip_before_action :current_user, only: [:new, :create]  #sign up : no object
    skip_before_action :logged_in?, only: [:new, :create]
    skip_before_action :redirect_if_not_logged_in, only: [:new, :create]

    # def index 
    #     @users = User.all
    # end
    def show
        prevent_user
    end



    def new 
        if logged_in?
            flash[:message] = "You are already logged in!"
            redirect_to pages_path
        else
            @user = User.new
        end
    end

    def create 
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to pages_path
        else

            render :new
        end

    end





    def edit
        prevent_user
    end 

    def update
        if @user.update(user_params)
        flash[:message] = "Succesfully Updated"
        redirect_to user_path(@user)
        else
        render :edit
        end

    end


    def destroy
        @user.destroy
        flash[:message] = "You've successfully deleted your account!"
        redirect_to root_path

    end





    private 

    def find_user
        @user = User.find_by_id(params[:id])
    end

    def user_params
        params.require(:user).permit(:username, :email, :password) 

    end

    def prevent_user
        if current_user.id != params[:id].to_i
            flash[:message] = " Something went wrong here. Please try again! "
            redirect_to root_path
        end
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render partial: 'layouts/errors', locals:{object: @user}%>

<h2>Edit <%= @user.username %> </h2>


    <%= form_with model: @user do |f| %>

    <%= f.label "username" %>
    <%= f.text_field :username, placeholder: @user.username%><br>

    <%= f.label "Email" %>
    <%= f.email_field :email, placeholder: @user.email%><br><br>


    <%= f.submit "Edit ✔", :class => "button"%>

    or <%= link_to "DELETE Your Account ␡", @user, method: :delete, :class => "button"  %> </p>


<% end %>

app/views/users/index.html.erb
<h1> User index page  ==> don't need this page anymore</h1>

<ul>
<% @users.each do |user| %>
<li><%= user.username %></li>
<% end %>
</ul>

app/views/users/new.html.erb
<%= render partial: 'layouts/errors', locals:{object: @user}%>


<h2>Please Sign Up For Rate My Hair Stylist!</h2>


<%= form_with model: @user, url: '/signup' do |f| %>
<%= f.label "Username" %>
<%= f.text_field :username, placeholder: true%>
<%= f.label "Email" %>
<%= f.email_field :email, placeholder: true %>
<%= f.label "Password" %>
<%= f.password_field :password, placeholder: true  %><br>



<%= f.submit "Signup 😜", :class => "button"%>

<%end%><br><br>

app/views/users/show.html.erb
<h2>Here is your Info.</h2>

<head>
    <style>
        table, th, td {
        border: 1px solid black;
        }
        th, td {
        padding: 10px;
        text-align: left;
        }
    </style>
</head>

<table style="width:25%">
  <thead>
    <tr>
      <th>Username</th>
      <th>email</th>
      
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= current_user.username %></td>
        <td><%= current_user.email %></td>
        
      </tr>
  </tbody>
</table>

<p><%= link_to "EDIT Your Profile", edit_user_path(@user), :class => "button" %></p>

<br>

<h3> Here is your previous haircut date ! </h3>
<ul>


    <% if @user.user_stylists.size == 0 %>
        "No reviews written yet. Let's add some reviews!"
        <%= link_to "Add a Review", new_user_user_stylist_path(@user), :class => "button" %>

    <% else %>
        <% @user.user_stylists.order(haircut_date: :desc).each do |user_stylist| %>
        <li><%= link_to user_stylist.datetime, user_user_stylist_path(@user, user_stylist) %>, 
        by hairstylist : <%= link_to user_stylist.stylist.name, stylist_path(user_stylist.stylist)%></li>
    
    <% end %>


<% end %>


</ul>

<br>
<h3>Click here to see your reviews </h3>
<p><%= link_to "Your Reviews", user_user_stylists_path(@user), :class => "button" %></p>
<br><br>