config/routes.rb
Rails.application.routes.draw do


root "sessions#welcome"
get 'pages', to: 'pages#index'#, as:'pages'  


####### OmniAuth #################   google ###################################
# get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
get '/auth/:provider/callback', to: 'sessions#omniauth'  #<= makes more dynamic
###############################################################################


########  SIGN UP ROUTES (custom)  ######## 
get '/signup', to: "users#new"
post '/signup', to: "users#create"


########  SESSIONS ROUTES  ########
get 'login', to: "sessions#new"
post 'login', to: "sessions#create"
delete 'logout', to: "sessions#destroy"
#################################################################



#################rested routes####################################
  resources :users, :except => [:index] do
    resources :user_stylists
  end
  resources :user_stylists

  resources :stylists, :except => [:destroy]

#################################################################


# match '*path' => redirect('/'), :via => [:get, :post] 
### localhost:3000/qwefkfqasdkfas;dlkfn to the root path/

end











# 🚧 # THINGS WE HAVE TO BUILD OUT
# get 'welcome', to: "sessions#welcome" 
# 🚧 #
######## 
# REMEMBER FOLKS  ::  NO resource :sessions 
#################################################################



  # get 'stylists/index'
  # get 'stylists/show'
  # get 'stylists/new'
  # get 'stylists/create'
  # get 'stylists/edit'
  # get 'stylists/update'
  # get 'stylists/destroy'
  # get 'sessions/new'
  # get 'sessions/create'
  # get 'sessions/login'
  # get 'sessions/destroy'
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/stylist.rb
class Stylist < ApplicationRecord
    has_many :user_stylists
    has_many :users, through: :user_stylists

   
    validates_presence_of :name, :phone, :shop_name, :address
    validates :phone, :presence => true, :phone => true
    
    ##### make upcase, downcase as the same name #####
    validates :name, uniqueness: { case_sensitive: false }
    validates_uniqueness_of :phone, :case_sensitive => false
  
  #################LIVE CODING #####################
    def self.search(params)
      where("Lower(name) LIKE ? ", "%#{params}%")
    end
  ###################################################










    #single hair stylist average rating#
    def average_rating
        UserStylist.where(stylist_id: self.id).average(:stars).to_f.round(1)
        #find @stylist and make average of stars from @stylist.user_stylist where @stylist id and user_Stylist stylist_id matched.  and then make it float value and round from the first decimal place.
    end


  # hairstylist name by alphabeical order 
    scope :alphabetical_order, -> { order(:name) }
      # def self.alphabetical_order
      #   order(:name)
      # end




  # Most Reviewed Hairstylists!! on PAGES#INDEX
    scope :most_reviews, -> {(joins(:user_stylists)
      .group('stylists.id')
      .order('count(user_stylists.id) desc', 'stylists.name ASC')
      .limit(10)
    )}

  
  # Top 5 high rated hairstylists (more than 3 reviews) on PAGES#INDEX
    scope :overall_ratings_more_than_3_reviews, -> {(joins(:user_stylists)
      .group('stylists.id')
      .having('count(stylists.id)>2')
      .order('avg(stars) desc')
      .limit(5)
    )}

      
end

app/controllers/stylists_controller.rb
class StylistsController < ApplicationController
  before_action :find_stylist, only: [:show, :edit, :update]


  def index
      @stylists = Stylist.alphabetical_order 
      
    ############ Live Coding #################################
      if params[:query] && !params[:query].empty?
        @stylists = @stylists.search(params[:query].downcase)
      end
    ##########################################################
  end

  def show
      if @stylist == nil
        redirect_to stylists_path
      end
  end



  def new
      @stylist = Stylist.new
  end


  def create
      @stylist = Stylist.new(stylist_params)

    if @stylist.save
        flash[:message] = "You've successfully created a new Hairstylist named #{@stylist.name.upcase}."
        redirect_to new_user_user_stylist_path(@user) #directly send the user to the review page 
    else
        render :new
    end

  end



  def edit
  end


  def update

    if @stylist.update(stylist_edit_params)
      flash[:message] = "Successfully Updated! "
      redirect_to stylist_path(@stylist)
    else
      render :edit
    end
    
  end






  private 

    def find_stylist
      @stylist= Stylist.find_by_id(params[:id])
    end

    def stylist_params
      params.require(:stylist).permit(:name, :phone, :shop_name, :address) 
    end

    def stylist_edit_params
      params.require(:stylist).permit(:phone, :shop_name, :address)
    end

end




# understand the challenge

# step 1 , don't code, pseudo code

# create a search bar on stylists homepage to search stylists by name ( partial string match )


# break it down into smaller steps (in order of request response)

    # 1. Where does the response originate? 
            # => Form on the stylists index page

    # 2. Create a route for the form to go to a controller action(index action or other action)
            # => index action 

    # 3. Write logic in controller ( or model) to filter by query
        #in stylist controller
          # => if params[:query] && !params[:query].empty?
          # =>   @stylists = @stylists.search(params[:query].downcase)
        #in stylist.rb   <=== where partial string match!!!!
          # def self.search(params)
          #   where("Lower(name) LIKE ? ", "%#{params}%")
          # end

    # 4. display results on index page or new view
         # boom on index page!!

app/helpers/stylists_helper.rb
module StylistsHelper

    # def stylist_name(stylist)
    #     "#{stylist.name}" +" working at "+ "#{stylist.address}"
    # end

end

app/views/stylists/edit.html.erb
<%= render partial: 'layouts/errors', locals:{object: @stylist}%>

<h2>Edit Hairstylist <%= @stylist.name %> !! </h2>

<br>
<div>

    Name : <span style="color:SlateBlue;font-weight:bold"> <%= @stylist.name %> </span><br>

<br><br>

            <%= form_for @stylist do |f| %>

                <%= f.label :phone, "Phone ☎️"%>
                <%= f.text_field :phone,  placeholder: "111-111-1111", pattern: "[0-9]{3}-[0-9]{3}-[0-9]{4}" %><br>
                <%= f.label :shop_name, "Shop Name 🏪" %>
                <%= f.text_field :shop_name %><br>
                <%= f.label :address, "Address 🌇" %>
                <%= f.text_field :address, style: 'width:30em' %><br><br>

        <%= f.submit "Update Hairstylist", :class => "button" %>
        <% end %>

</div>

app/views/stylists/index.html.erb
<h2> We have total <span style="color:crimson;"> <%= @stylists.size %> </span> <%= "hairstylist".pluralize(@stylists.size) %> </h2>




<!-- ############LIVE CODING  :  Build a Search bar to find by stylist name #########-->
      <%= form_with url: "/stylists", method: :get do |form| %>
        <%= form.label :query, "Search for Hairstylist Name :" %>
        <%= form.text_field :query %>
        <%= form.submit "Search" %>
      <% end %>
<!--#################################################################################-->



  <ul class="split">
  <!-- all hairlists list -->
      <% @stylists.each do |stylist| %>
        <li>
            <p>
            <!-- ### hairstylist average rating### -->
            <b><%= link_to stylist.name, stylist_path(stylist) %> </b><br>
            Overall rating : <span style="color:crimson;"><%= stylist.average_rating %></span>,  
            Total reviews : <span style="color:crimson;"><%= stylist.user_stylists.size %></span>

            </p>
        </li>
      <% end %>

  </ul>

app/views/stylists/new.html.erb
<%= render partial: 'layouts/errors', locals:{object: @stylist}%>

<h2>Create a New Hairstylist !! </h2>

<br>
<div>
        <%= form_for @stylist do |f| %>

                <%= f.label :name %>
                <%= f.text_field :name %><br>
                <%= f.label :phone %>
                <%= f.telephone_field :phone, placeholder: "111-111-1111", pattern: "[0-9]{3}-[0-9]{3}-[0-9]{4}" %><br>
                <%= f.label :shop_name %>
                <%= f.text_field :shop_name %><br>
                <%= f.label :address %>
                <%= f.text_field :address %><br>

        <%= f.submit "Create a new Hair Stylist!", :class => "button" %>
        <% end %>

</div>

app/views/stylists/show.html.erb
<h1>✂️ <%= @stylist.name %> details ✂️</h1>
    
    <ul>
        <li>Name : <span style="color:SlateBlue;font-weight:bold"> <%= @stylist.name %> </span><br>
        Phone ☎️ : <%= @stylist.phone %><br>
        Shop Name : <span style="color:red;"> <%= @stylist.shop_name %> </span> <br>
        Address : <span style="color:green;">  <%= @stylist.address %></span><br>
        Overall Rating : <%= @stylist.average_rating %> / 5.0 <br>
        Edit : <%= link_to @stylist.name, edit_stylist_path(@stylist) %>
        </li>
        <br>
    </ul>



<h2>✂️ CUSTOMER  REVIEWS  FOR  ❝ <%= @stylist.name.upcase %> ❞ ✂️ </h2>
        <h3> Total <%= @stylist.user_stylists.size %> <%= pluralize_without_count(@stylist.user_stylists.count, 'review', ':') %></h3> 
 
    <ul> 
        <% @stylist.user_stylists.order(haircut_date: :desc).each do |all_comments| %>
            <li><span style="color:SlateBlue;font-weight:bold"> Date: <%= all_comments.datetime %> </span> <br> 
                <b>"<%= all_comments.user.username %>"</b> says, <%= all_comments.comment %><br>
                Rating : <% all_comments.stars.times do  %><span class="star">⭐️</span><% end %> <br><br>
            </li>
        <% end %>
    </ul>