config/routes.rb
Rails.application.routes.draw do


root "sessions#welcome"
get 'pages', to: 'pages#index'#, as:'pages'  


####### OmniAuth #################   google ###################################
# get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
get '/auth/:provider/callback', to: 'sessions#omniauth'  #<= makes more dynamic
###############################################################################


########  SIGN UP ROUTES (custom)  ######## 
get '/signup', to: "users#new"
post '/signup', to: "users#create"


########  SESSIONS ROUTES  ########
get 'login', to: "sessions#new"
post 'login', to: "sessions#create"
delete 'logout', to: "sessions#destroy"
#################################################################



#################rested routes####################################
  resources :users, :except => [:index] do
    resources :user_stylists
  end
  resources :user_stylists

  resources :stylists, :except => [:destroy]

#################################################################


# match '*path' => redirect('/'), :via => [:get, :post] 
### localhost:3000/qwefkfqasdkfas;dlkfn to the root path/

end











# 🚧 # THINGS WE HAVE TO BUILD OUT
# get 'welcome', to: "sessions#welcome" 
# 🚧 #
######## 
# REMEMBER FOLKS  ::  NO resource :sessions 
#################################################################



  # get 'stylists/index'
  # get 'stylists/show'
  # get 'stylists/new'
  # get 'stylists/create'
  # get 'stylists/edit'
  # get 'stylists/update'
  # get 'stylists/destroy'
  # get 'sessions/new'
  # get 'sessions/create'
  # get 'sessions/login'
  # get 'sessions/destroy'
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/user_stylist.rb
class UserStylist < ApplicationRecord
    belongs_to :user
    belongs_to :stylist
    # belongs_to :stylist, optional: true


    validates_presence_of :haircut_date, :stars,:services, :price, :comment
    validates :price, format: { with: /\A\d+(?:\.\d{0,2})?\z/ }, numericality: { greater_than: 0, less_than: 2000 }
    validates :comment, length: { minimum: 2, maximum: 1000,
      too_short: "%{count} characters is the minimum allowed", 
      too_long: "%{count} characters is the maximum allowed" }
    
    # haircut_date custom validation  
    validate :haircut_date_cannot_be_in_the_future
      def haircut_date_cannot_be_in_the_future
        errors.add(:haircut_date, "can't be in the future") if
          !haircut_date.blank? and haircut_date > Date.today
      end



    ######### Recently High-Rated Reviews on PAGES#INDEX ################
    scope :stars_more_than, ->(amount) { 
      where('stars > ?', amount)
      .order(haircut_date: :desc)
      .limit(5)
    }


    #############Recent Haircut Reviews on PAGES#INDEX###################
    scope :recent_haircut_date_reviews, -> { 
      order(haircut_date: :desc) 
      .limit(5) 
      }


    #########order by haircut_date(desc) for user_stylist index  page #############
    scope :recent_haircut_date_order, -> { order(haircut_date: :desc) }

    def datetime
      self.haircut_date.strftime("%m/%d/%Y") if self.haircut_date
    end


end





 




# accepts_nested_attributes_for :stylist, :reject_if => proc { |attributes| attributes['name, phone, shop_name, address'].blank? }

app/controllers/user_stylists_controller.rb
class UserStylistsController < ApplicationController
    before_action :find_user_stylist#,  only: [:index, :show, :new, :create, :edit, :update, :destroy]

    def index 
        if params[:user_id]
            #order by haircut date
            @user_stylists = current_user.user_stylists.recent_haircut_date_order
        else
            @user_stylists = UserStylist.recent_haircut_date_order
        end
    end

    
    def show
        find_stylist_id_on_user_stylist
    end


    def new
        
        @user_stylist = current_user.user_stylists.build
    end

    def create 
        @user_stylist = current_user.user_stylists.build(user_stylist_params)

        if  @user_stylist.save
            flash[:message] = "Your review with hairstylist #{@user_stylist.stylist.name.upcase} has been created"
            redirect_to user_user_stylist_path(@user, @user_stylist)
            
        else

            render :new
        end
        

    end







    def edit
        if @user_stylist.user_id != current_user.id

            flash[:message] = " Something went wrong here. Please try again! "
            redirect_to root_path
        
        end

    end

    def update
        if @user_stylist.update(user_stylist_params)

            flash[:message] = "Your review has been updated! "
            redirect_to user_user_stylist_path(@user, @user_stylist)
        else
            render :edit

        end

        
    end

    def destroy
        @user_stylist.destroy
        flash[:message] = "Your review has been deleted! "
        redirect_to user_user_stylists_path(@user)
    end




    

    private


    def find_user_stylist
        @user_stylist= UserStylist.find_by_id(params[:id])
    end


    def find_stylist_id_on_user_stylist
        params[:stylist_id_on_user_stylist] = @user_stylist.stylist_id
        @stylist = Stylist.find_by_id(params[:stylist_id_on_user_stylist]) 
    end


    def user_stylist_params
        params.require(:user_stylist).permit(:haircut_date, :stars, :comment, 
            :services, :price, :user_id, :stylist_id)
    end 




end


# understand the challenge

# step 1 , don't code, pseudo code

# create a search bar on stylists homepage to search stylists by name ( partial string match )


# break it down into smaller steps (in order of request response)

    # 1. Where does the response originate? Form on the stylists index page
    # 2. Create a route for the form to go to a controller action(index action or other action)
            # => I index action 
    # 3. Write logic in controller ( or model) to filter by query
    # 4. display results on index page or new view

app/helpers/user_stylists_helper.rb
module UserStylistsHelper

    # def list_with_names(user_stylist)
    #     user_stylist.stylist.name
    # end
end

app/views/user_stylists/_form.html.erb
<%= render partial: 'layouts/errors', locals:{object: @user_stylist}%>

<%= form_with model: @user_stylist do |f| %> 
        Your Hairstylist Name
   <%= f.collection_select :stylist_id, Stylist.order('created_at DESC').all, :id, :name, 
    {:prompt => true} %> <br>

 <!-- <%= select("user_stylist", "stylist_id", Stylist.all.collect { |p| [ p.name, p.id ] }, { include_blank: 'None' }) %> -->

<br>
    <% if params[:id] == nil   %>
        or→ <%= link_to "🤯Create a New Hair Stylist🤯", new_stylist_path %> <br><br>
    <% end %>
<br>



        <%= f.label :haircut_date, "Haircut Date" %>
        <%= f.date_field :haircut_date %><br>
        <%= f.label :stars, "Rating" %>
        <%= f.select(:stars, options_for_select([
            ["⭐️", 1],
            ["⭐️⭐️", 2],
            ["⭐️⭐️⭐️", 3],
            ["⭐️⭐️⭐️⭐️", 4],
            ["⭐️⭐️⭐️⭐️⭐️", 5]
            ], selected: @user_stylist.stars)) %> <br>
        <%= f.label :services, "Services" %>
        <%= f.text_field :services %><br>
        <%= f.label :price, "Price" %>
        <%= f.number_field :price, step: :any %><br><br>
        <%= f.label :comment, "Comment your hairstylist" %>
        <%= f.text_area :comment %><br>
        <br><br>

            <%= f.submit "submit", :class => "button"%>
<% end %>

app/views/user_stylists/edit.html.erb
<h1>Edit this Review </h1>

<%= render 'form' %> 

<%= button_to "DELETE this review", @user_stylist, :class => "button", method: :delete %>

    

app/views/user_stylists/index.html.erb
<% if params[:user_id] %>
    <h2> You have total <span style="color:crimson;"> <%= @user_stylists.all.size %> </span> <%= "review".pluralize(current_user.user_stylists.size) %> </h2>
<% else %> 
<h2> We have total <span style="color:crimson;"> <%= @user_stylists.all.size %> </span> <%= "review".pluralize(UserStylist.all.size) %> </h2>
<% end %>



    <ul class="split">
        <% @user_stylists.each do |user_stylist| %>
            <li>
        
                <%if user_stylist.user_id == current_user.id %>
                    
                    <span style="color:red"> 
                    <b>Date : <i><%= link_to user_stylist.datetime, user_user_stylist_path(@user, user_stylist) %></i> 
                    </span>  ⬅ ⬅ ⬅ ⬅ ⬅ ⬅ ⬅ ⬅ ⬅ ⬅ ⬅ ⬅  👏 Your Review!! 👏 </b><br>
                    ✄ Hairstylist Name : <span style="color:DarkCyan;"> <%= user_stylist.stylist.name %> </span> <br>
                    ✄ Rating : <% user_stylist.stars.times do %><span class="star">⭐️</span><% end %><% (5 - user_stylist.stars).times do %><span class="out-of">☆</span><% end %><br>
                    ✄ Service : <span style="color:green;"> <%= user_stylist.services %> </span> <br><br>
    

                <%else%>
                
                    <span style="color:SlateBlue;font-weight:bold"> 
                    Date : <i><%= link_to user_stylist.datetime, user_stylist_path(user_stylist) %></i>
                    </span><br>
                    ✄ Hairstylist Name : <span style="color:DarkCyan;"> <%= user_stylist.stylist.name %> </span> <br>
                    ✄ Rating : <% user_stylist.stars.times do %><span class="star">⭐️</span><% end %><% (5 - user_stylist.stars).times do %><span class="out-of">☆</span><% end %><br>
                    ✄ Service : <span style="color:green;"> <%= user_stylist.services %> </span> <br><br>
                <% end %>

            </li>

        <% end %>

    </ul>

app/views/user_stylists/new.html.erb
<h2> Rate your hairstylist here! </h2>

<%= render 'form' %>

<br><br>

app/views/user_stylists/show.html.erb
<h1> Review Details </h1>


  <ul class="a">

    <li>
        Date : <i><span style="color:SlateBlue;font-weight:bold"> <%= @user_stylist.datetime %></i><br><br>
          ✄ Hair Stylist Name : <span style="color:red;"> <%= @user_stylist.stylist.name  %> </span>  (💇🏻‍<%= link_to "Hairstylist Info ☎", stylist_path(@stylist) %>)<br><br>
          ✄ Rating : <% @user_stylist.stars.times do %><span class="star">⭐️</span><% end %></span><% (5 - @user_stylist.stars).times do %><span class="out-of">☆</span><% end %><br><br>
          ✄ Service :  <span style="color:red;">  <%= @user_stylist.services %> </span><br><br>
          ✄ Price : <span style="color:red;"> $<%= @user_stylist.price %> </span> <br><br>
          ✄ Comment : <span style="color:green;"> <%= @user_stylist.comment %> </span> <br><br>
          ✄ Written by (username): <span style="color:blue;"> <%= @user_stylist.user.username %> </span> <br><br>
    </li>

  </ul>
<%if params[:user_id] && @user_stylist.user_id == current_user.id %>

   <!-- 💁💫 <%= link_to "EDIT Your Review", edit_user_user_stylist_path(@user, @user_stylist) %> 💁💫 -->
  <%= button_to "Edit your review",  edit_user_user_stylist_path(@user, @user_stylist), :class => "button", :method => :get  %>
<%end %>