config/routes.rb
Rails.application.routes.draw do


root "sessions#welcome"
get 'pages', to: 'pages#index'#, as:'pages'  


####### OmniAuth #################   google ###################################
# get '/auth/google_oauth2/callback', to: 'sessions#omniauth'
get '/auth/:provider/callback', to: 'sessions#omniauth'  #<= makes more dynamic
###############################################################################


########  SIGN UP ROUTES (custom)  ######## 
get '/signup', to: "users#new"
post '/signup', to: "users#create"


########  SESSIONS ROUTES  ########
get 'login', to: "sessions#new"
post 'login', to: "sessions#create"
delete 'logout', to: "sessions#destroy"
#################################################################



#################rested routes####################################
  resources :users, :except => [:index] do
    resources :user_stylists
  end
  resources :user_stylists

  resources :stylists, :except => [:destroy]

#################################################################


# match '*path' => redirect('/'), :via => [:get, :post] 
### localhost:3000/qwefkfqasdkfas;dlkfn to the root path/

end











# 🚧 # THINGS WE HAVE TO BUILD OUT
# get 'welcome', to: "sessions#welcome" 
# 🚧 #
######## 
# REMEMBER FOLKS  ::  NO resource :sessions 
#################################################################



  # get 'stylists/index'
  # get 'stylists/show'
  # get 'stylists/new'
  # get 'stylists/create'
  # get 'stylists/edit'
  # get 'stylists/update'
  # get 'stylists/destroy'
  # get 'sessions/new'
  # get 'sessions/create'
  # get 'sessions/login'
  # get 'sessions/destroy'
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>
 
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li style="color: crimson;"><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_nav.erb
<br>
<% if !logged_in? %>
<br>
    <div id="navbar">
    <%= button_to "Log in with Google", '/auth/google_oauth2',:class => "button"  %>
    <%= button_to "Sign Up", signup_path, :class => "button",  :method => :get  %> 
    <%= button_to "Log In",  login_path, :class => "button", :method => :get  %> 
    </div>  

<% else %>


         <h4>
         <b>|| 🤩<%= link_to "Main", pages_path %>🤩 ||
         🤩<%= link_to "Your Reviews", user_user_stylists_path(@user) %>🤩 ||
         🤩<%= link_to "Add a Review", new_user_user_stylist_path(@user) %>🤩 ||
         🤩<%= link_to "All Reviews", user_stylists_path %>🤩 || 
     
         💇‍♂️<%= link_to "Add a Hairstylist", new_stylist_path %> 💆‍♂️ ||
         🤩<%= link_to "All Hairstylists", stylists_path %>🤩 ||

 
        


        🤯<%= link_to "Your Profile", user_path(@user) %>🤯 ||
        💥<%= link_to "Log Out", logout_path,  method: :delete %> 💥 ||
        </b>
        </h4>
          <h1>   💇‍♂️  Hello,  <%= current_user.username.upcase %>!  💇🏻‍♂️ ‍</h1>



<% end %>


<hr>

app/views/layouts/application.html.erb
<html>
  <head>
    <title>RateMyHairstylist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <%= render 'layouts/nav' %>
    </div>


    <div>

      <% if flash[:message] %>
          <p style="color: crimson;"><b><%= flash[:message] %></b></p>
      <% end %>
    
    </div>

    <%= yield %>

  </body>
</html>